version: "3.8"

services:
  mysql:
    image: mysql:8.0.32
    command: |
      --default-authentication-plugin=mysql_native_password
      --innodb-log-file-size=100M
      --innodb-log-files-in-group=2
      --max-allowed-packet=30M
      --bind-address=*
      --log_bin_trust_function_creators=1
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_USER=${USER}
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

  eset-protect-server:
    build:
      context: .
      dockerfile: Dockerfile-eset-protect-server
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      - DB_ADMIN_USERNAME=${USER}
      - DB_ADMIN_PASSWORD=${PASSWORD}
    volumes:
      - eset-protect-server-config:/config
      - eset-protect-server-data:/data
      - eset-protect-server-logs:/logs
    ports:
      - 2222:2222

  eset-protect-console:
    build:
      context: .
      dockerfile: Dockerfile-eset-protect-console
    depends_on:
      - eset-protect-server
    restart: unless-stopped
    volumes:
      - eset-protect-console:/config
    ports:
      - 8080:8080

volumes:
  mysql:
  eset-protect-server-config:
  eset-protect-server-data:
  eset-protect-server-logs:
  eset-protect-console:
